[workspace]
resolver = "2"
members = [
    "copy-vars",
    "platform",
    "platform-scan",
    # "stream-test",
    # "monitor-activities",
    # "activity-logs",
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json"] }
