---
frameworks:
  drupal:
      - drupal/core
      - drupal/drupal
  wordpress:
    - johnpbloch/wordpress-core
    - roots/wordpress
  laravel:
    - laravel/framework
  symfony:
    - symfony/symfony
    - symfony/flex
packages:
  - drupal/xray_audit # SA-CONTRIB-2023-012
  - guzzlehttp/guzzle
  - laravel/nova